# Generated by Django 6.0.2 on 2026-02-27 06:27

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EligibleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ug_number', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('is_registered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_open', models.BooleanField(default=True)),
                ('reveal_open', models.BooleanField(default=False)),
                ('countdown_datetime', models.DateTimeField(blank=True, null=True)),
                ('reveal_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('ug_number', models.CharField(max_length=50)),
                ('reveal_token', models.CharField(default=base.models._generate_token, editable=False, unique=True)),
                ('has_revealed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_from', to='base.participant')),
                ('eligible_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.eligiblestudent')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='base.event')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('event', 'ug_number')},
            },
        ),
    ]
